repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks
        name: gitleaks (protect)
        args:
          - protect
          - --staged
          - --config=./gitleaks.toml
